controller_manager:
  ros__parameters:
    update_rate: 100

diff_drive_controller:
  ros__parameters:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    cmd_vel_timeout: 0.25
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    publish_rate: 50
